import { beforeAll, beforeEach, describe, expect, it } from 'vitest';
import { newDb } from 'pg-mem';
import type { Pool } from 'pg';
import { migrateUp } from '../../src/database/migrations.js';
import { UserRepository } from '../../src/database/repositories/user-repository.js';
import { ChainRepository } from '../../src/database/repositories/chain-repository.js';
import { MonitoredAddressRepository } from '../../src/database/repositories/monitored-address-repository.js';
import { DetectedTransactionRepository } from '../../src/database/repositories/detected-transaction-repository.js';

const memory = newDb(); memory.public.registerFunction({ name: 'length', args: ['text'], returns: 'integer', implementation: (value: string) => value.length });
const adapter = memory.adapters.createPg(); const pool = new adapter.Pool() as unknown as Pool;
const repository = new DetectedTransactionRepository(pool);
const senderA = '0x0000000000000000000000000000000000000011'; const senderB = '0x0000000000000000000000000000000000000022';
let chainId: string; let monitoredId: string;
const input = (hash: string, sender: string, nonce: bigint, observedAt = new Date()) => ({ monitoredAddressId: monitoredId, chainId, transaction: { hash, from: sender, to: null, nonce, value: 0n, input: '0x', gas: 21_000n, gasPrice: 1n, maxFeePerGas: null, maxPriorityFeePerGas: null }, observation: { hash, observedAt, provider: 'test-provider' } });

describe('pending source transaction lifecycle', () => {
  beforeAll(async () => { await migrateUp(pool); });
  beforeEach(async () => { await pool.query('DELETE FROM execution_requests'); await pool.query('DELETE FROM copy_transaction_proposals'); await pool.query('DELETE FROM detected_mints'); await pool.query('DELETE FROM detected_transactions'); await pool.query('DELETE FROM monitoring_checkpoints'); await pool.query('DELETE FROM monitored_addresses'); await pool.query('DELETE FROM chains'); await pool.query('DELETE FROM users'); const user = await new UserRepository(pool).create('9001'); const chain = await new ChainRepository(pool).create('9001', 'Pending'); chainId = chain.id; monitoredId = (await new MonitoredAddressRepository(pool).create({ userId: user.id, chainId, walletAddress: senderA })).id; });
  it('is idempotent across duplicate observations and restart-like reprocessing', async () => { const hash = '0x' + '1'.repeat(64); const first = await repository.upsertPending(input(hash, senderA, 1n)); const second = await repository.upsertPending(input(hash, senderA, 1n)); expect(second.id).toBe(first.id); expect(Number((await pool.query('SELECT COUNT(*) count FROM detected_transactions')).rows[0].count)).toBe(1); });
  it('marks same-sender same-nonce replacement', async () => { const first = await repository.upsertPending(input('0x' + '2'.repeat(64), senderA, 2n)); const second = await repository.upsertPending(input('0x' + '3'.repeat(64), senderA, 2n)); const row = await pool.query('SELECT status, replacement_transaction_id FROM detected_transactions WHERE id = $1', [first.id]); expect(row.rows[0]).toMatchObject({ status: 'REPLACED', replacement_transaction_id: Number(second.id) }); });
  it('does not replace same sender with a different nonce', async () => { await repository.upsertPending(input('0x' + '4'.repeat(64), senderA, 3n)); await repository.upsertPending(input('0x' + '5'.repeat(64), senderA, 4n)); expect(Number((await pool.query("SELECT COUNT(*) count FROM detected_transactions WHERE status = 'PENDING'")).rows[0].count)).toBe(2); });
  it('does not replace a different sender with the same nonce', async () => { await repository.upsertPending(input('0x' + '6'.repeat(64), senderA, 5n)); await repository.upsertPending(input('0x' + '7'.repeat(64), senderB, 5n)); expect(Number((await pool.query("SELECT COUNT(*) count FROM detected_transactions WHERE status = 'PENDING'")).rows[0].count)).toBe(2); });
  it('marks stale pending transactions dropped', async () => { const old = new Date(Date.now() - 60_000); await repository.upsertPending(input('0x' + '8'.repeat(64), senderA, 6n, old)); await repository.markDroppedBefore(new Date()); expect((await pool.query('SELECT status FROM detected_transactions')).rows[0].status).toBe('DROPPED'); });
  it('reconciles a pending transaction as mined and preserves first seen', async () => { const hash = '0x' + '9'.repeat(64); const first = await repository.upsertPending(input(hash, senderA, 7n)); await repository.markMined(hash, 99n); const row = await pool.query('SELECT status, mined_block_number, first_seen_at FROM detected_transactions WHERE id = $1', [first.id]); expect(row.rows[0].status).toBe('MINED'); expect(String(row.rows[0].mined_block_number)).toBe('99'); expect(row.rows[0].first_seen_at).toEqual(first.firstSeenAt); });
  it('records reverted source transactions', async () => { const hash = '0x' + 'a'.repeat(64); await repository.upsertPending(input(hash, senderA, 8n)); await repository.markMined(hash, 100n, true); expect((await pool.query('SELECT status FROM detected_transactions')).rows[0].status).toBe('REVERTED'); });
  it('records observation, ingestion, and analysis latency timestamps', async () => { const observedAt = new Date(Date.now() - 10); const saved = await repository.upsertPending(input('0x' + 'b'.repeat(64), senderA, 9n, observedAt)); const started = new Date(); const completed = new Date(started.getTime() + 2); await repository.markAnalysisTiming(saved.id, started, completed); const row = await pool.query('SELECT observed_at, ingested_at, analysis_started_at, analysis_completed_at, provider_observation FROM detected_transactions WHERE id = $1', [saved.id]); expect(row.rows[0]).toMatchObject({ observed_at: observedAt, analysis_started_at: started, analysis_completed_at: completed, provider_observation: 'test-provider' }); expect(row.rows[0].ingested_at).toBeInstanceOf(Date); });
});
