CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  telegram_user_id BIGINT NOT NULL UNIQUE,
  username TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE chains (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chain_id BIGINT NOT NULL UNIQUE CHECK (chain_id > 0),
  name TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE monitored_addresses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  chain_id BIGINT NOT NULL REFERENCES chains(id) ON DELETE RESTRICT,
  wallet_address VARCHAR(42) NOT NULL CHECK (
    wallet_address = LOWER(wallet_address)
    AND LENGTH(wallet_address) = 42
    AND wallet_address LIKE '0x%'
  ),
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT monitored_addresses_user_chain_wallet_unique
    UNIQUE (user_id, chain_id, wallet_address)
);

CREATE INDEX monitored_addresses_wallet_address_idx ON monitored_addresses(wallet_address);
CREATE INDEX monitored_addresses_chain_enabled_idx ON monitored_addresses(chain_id, enabled);
CREATE INDEX monitored_addresses_user_id_idx ON monitored_addresses(user_id);

CREATE TABLE detected_mints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  monitored_address_id BIGINT NOT NULL REFERENCES monitored_addresses(id) ON DELETE CASCADE,
  chain_id BIGINT NOT NULL REFERENCES chains(id) ON DELETE RESTRICT,
  source_transaction_hash VARCHAR(66) NOT NULL CHECK (
    source_transaction_hash = LOWER(source_transaction_hash)
    AND LENGTH(source_transaction_hash) = 66
    AND source_transaction_hash LIKE '0x%'
  ),
  block_number BIGINT NOT NULL CHECK (block_number >= 0),
  contract_address VARCHAR(42) NOT NULL CHECK (
    contract_address = LOWER(contract_address)
    AND LENGTH(contract_address) = 42
    AND contract_address LIKE '0x%'
  ),
  function_selector VARCHAR(10),
  function_name TEXT,
  transaction_value NUMERIC(78, 0) NOT NULL CHECK (transaction_value >= 0),
  detected_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status TEXT NOT NULL DEFAULT 'detected' CHECK (status IN ('detected', 'reviewed', 'dismissed')),
  CONSTRAINT detected_mints_monitored_transaction_unique
    UNIQUE (monitored_address_id, source_transaction_hash)
);

CREATE INDEX detected_mints_source_transaction_hash_idx ON detected_mints(source_transaction_hash);
CREATE INDEX detected_mints_contract_address_idx ON detected_mints(contract_address);
CREATE INDEX detected_mints_chain_detected_at_idx ON detected_mints(chain_id, detected_at DESC);
CREATE INDEX detected_mints_status_idx ON detected_mints(status);
