CREATE TABLE detected_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  monitored_address_id BIGINT NOT NULL REFERENCES monitored_addresses(id) ON DELETE CASCADE,
  chain_id BIGINT NOT NULL REFERENCES chains(id) ON DELETE RESTRICT,
  transaction_hash VARCHAR(66) NOT NULL CHECK (transaction_hash = LOWER(transaction_hash) AND LENGTH(transaction_hash) = 66 AND transaction_hash LIKE '0x%'),
  block_number BIGINT NOT NULL CHECK (block_number >= 0),
  from_address VARCHAR(42) NOT NULL CHECK (from_address = LOWER(from_address) AND LENGTH(from_address) = 42 AND from_address LIKE '0x%'),
  to_address VARCHAR(42) CHECK (to_address IS NULL OR (to_address = LOWER(to_address) AND LENGTH(to_address) = 42 AND to_address LIKE '0x%')),
  transaction_value NUMERIC(78, 0) NOT NULL CHECK (transaction_value >= 0),
  input_data TEXT NOT NULL DEFAULT '0x',
  gas_limit NUMERIC(78, 0),
  gas_price NUMERIC(78, 0),
  effective_gas_price NUMERIC(78, 0),
  detected_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status TEXT NOT NULL DEFAULT 'detected' CONSTRAINT detected_transactions_status_check CHECK (status IN ('detected', 'confirmed', 'reorged')),
  CONSTRAINT detected_transactions_address_hash_unique UNIQUE (monitored_address_id, transaction_hash)
);

CREATE INDEX detected_transactions_hash_idx ON detected_transactions(transaction_hash);
CREATE INDEX detected_transactions_chain_block_idx ON detected_transactions(chain_id, block_number);
CREATE INDEX detected_transactions_from_address_idx ON detected_transactions(from_address);
CREATE INDEX detected_transactions_status_idx ON detected_transactions(status);

CREATE TABLE monitoring_checkpoints (
  chain_id BIGINT PRIMARY KEY REFERENCES chains(id) ON DELETE CASCADE,
  last_processed_block BIGINT NOT NULL CHECK (last_processed_block >= 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
