ALTER TABLE detected_mints RENAME TO detected_mints_legacy;

CREATE TABLE detected_mints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT detected_mint_events_pkey PRIMARY KEY,
  detected_transaction_id BIGINT NOT NULL REFERENCES detected_transactions(id) ON DELETE CASCADE,
  monitored_address_id BIGINT NOT NULL REFERENCES monitored_addresses(id) ON DELETE CASCADE,
  chain_id BIGINT NOT NULL REFERENCES chains(id) ON DELETE RESTRICT,
  transaction_hash VARCHAR(66) NOT NULL CHECK (transaction_hash = LOWER(transaction_hash) AND LENGTH(transaction_hash) = 66 AND transaction_hash LIKE '0x%'),
  nft_standard TEXT NOT NULL CHECK (nft_standard IN ('ERC721', 'ERC1155')),
  nft_contract_address VARCHAR(42) NOT NULL CHECK (nft_contract_address = LOWER(nft_contract_address) AND LENGTH(nft_contract_address) = 42 AND nft_contract_address LIKE '0x%'),
  token_id NUMERIC(78, 0) NOT NULL CHECK (token_id >= 0),
  quantity NUMERIC(78, 0) NOT NULL CHECK (quantity > 0),
  recipient_address VARCHAR(42) NOT NULL CHECK (recipient_address = LOWER(recipient_address) AND LENGTH(recipient_address) = 42 AND recipient_address LIKE '0x%'),
  block_number BIGINT NOT NULL CHECK (block_number >= 0),
  log_index INTEGER NOT NULL CHECK (log_index >= 0),
  batch_index INTEGER NOT NULL DEFAULT 0 CHECK (batch_index >= 0),
  detected_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status TEXT NOT NULL DEFAULT 'detected' CHECK (status IN ('detected', 'reviewed', 'dismissed')),
  CONSTRAINT detected_mints_event_unique UNIQUE (detected_transaction_id, log_index, batch_index)
);

CREATE INDEX detected_mints_transaction_idx ON detected_mints(detected_transaction_id);
CREATE INDEX detected_mints_hash_idx ON detected_mints(transaction_hash);
CREATE INDEX detected_mints_contract_token_idx ON detected_mints(nft_contract_address, token_id);
CREATE INDEX detected_mints_recipient_idx ON detected_mints(recipient_address);

ALTER TABLE detected_transactions ADD COLUMN analysis_status TEXT NOT NULL DEFAULT 'pending'
  CHECK (analysis_status IN ('pending', 'analyzing', 'analyzed', 'failed'));
ALTER TABLE detected_transactions ADD COLUMN analyzed_at TIMESTAMPTZ;
CREATE INDEX detected_transactions_analysis_status_idx ON detected_transactions(analysis_status);
