CREATE TABLE copy_transaction_proposals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  detected_mint_id BIGINT NOT NULL REFERENCES detected_mints(id) ON DELETE CASCADE,
  source_transaction_hash VARCHAR(66) NOT NULL,
  destination_wallet VARCHAR(42) NOT NULL,
  chain_id BIGINT NOT NULL REFERENCES chains(id) ON DELETE RESTRICT,
  strategy TEXT NOT NULL CHECK (strategy IN ('PUBLIC_MINT', 'MERKLE_ALLOWLIST', 'SIGNATURE_AUTHORIZED', 'UNKNOWN')),
  eligibility_status TEXT NOT NULL CHECK (eligibility_status IN ('ELIGIBLE', 'NOT_ELIGIBLE', 'ELIGIBILITY_UNKNOWN')),
  target_contract VARCHAR(42),
  calldata TEXT,
  native_value NUMERIC(78, 0),
  gas_limit NUMERIC(78, 0),
  simulation_status TEXT NOT NULL CHECK (simulation_status IN ('NOT_RUN', 'SUCCESS', 'REVERTED', 'FAILED')),
  simulation_error TEXT,
  proposal_status TEXT NOT NULL CHECK (proposal_status IN ('READY', 'ELIGIBILITY_REQUIRED', 'NOT_ELIGIBLE', 'ELIGIBILITY_UNKNOWN', 'UNSUPPORTED')),
  confidence TEXT NOT NULL CHECK (confidence IN ('HIGH', 'MEDIUM', 'LOW')),
  explanation TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT copy_proposals_source_destination_unique UNIQUE (chain_id, source_transaction_hash, destination_wallet)
);

CREATE INDEX copy_proposals_detected_mint_idx ON copy_transaction_proposals(detected_mint_id);
CREATE INDEX copy_proposals_status_idx ON copy_transaction_proposals(proposal_status);
CREATE INDEX copy_proposals_destination_idx ON copy_transaction_proposals(destination_wallet);
