ALTER TABLE copy_transaction_proposals ADD COLUMN user_id BIGINT REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE copy_transaction_proposals ADD COLUMN execution_status TEXT NOT NULL DEFAULT 'PENDING'
  CHECK (execution_status IN ('PENDING','READY','APPROVAL_REQUIRED','APPROVED','REJECTED','SUBMITTED','CONFIRMED','FAILED','EXPIRED'));
ALTER TABLE copy_transaction_proposals ADD COLUMN expires_at TIMESTAMPTZ;
UPDATE copy_transaction_proposals SET execution_status = CASE WHEN proposal_status = 'READY' THEN 'READY' ELSE 'FAILED' END;
CREATE INDEX copy_proposals_user_status_idx ON copy_transaction_proposals(user_id, execution_status);
CREATE INDEX copy_proposals_expires_at_idx ON copy_transaction_proposals(expires_at);

CREATE TABLE execution_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proposal_id BIGINT NOT NULL UNIQUE REFERENCES copy_transaction_proposals(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'APPROVED' CHECK (status IN ('APPROVED','SUBMITTED','CONFIRMED','FAILED')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
