ALTER TABLE copy_transaction_proposals ALTER COLUMN detected_mint_id DROP NOT NULL;
ALTER TABLE copy_transaction_proposals ADD COLUMN detected_transaction_id BIGINT REFERENCES detected_transactions(id) ON DELETE CASCADE;
ALTER TABLE copy_transaction_proposals ADD COLUMN mint_quantity NUMERIC(78, 0) NOT NULL DEFAULT 1;
ALTER TABLE copy_transaction_proposals ADD CONSTRAINT copy_proposal_source_check
  CHECK (detected_mint_id IS NOT NULL OR detected_transaction_id IS NOT NULL);

CREATE TABLE user_execution_settings (
  user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  execution_mode TEXT NOT NULL DEFAULT 'DISABLED' CHECK (execution_mode IN ('DISABLED','TELEGRAM_APPROVAL','AUTO')),
  destination_wallet VARCHAR(42),
  allowed_chains JSONB NOT NULL DEFAULT '[]'::jsonb,
  allowed_contracts JSONB NOT NULL DEFAULT '[]'::jsonb,
  max_native_value NUMERIC(78, 0),
  max_gas NUMERIC(78, 0),
  max_quantity NUMERIC(78, 0),
  proposal_expiration_seconds INTEGER NOT NULL DEFAULT 600 CHECK (proposal_expiration_seconds > 0),
  auto_retry_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE execution_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proposal_id BIGINT NOT NULL REFERENCES copy_transaction_proposals(id) ON DELETE CASCADE,
  source_transaction_hash VARCHAR(66) NOT NULL,
  destination_wallet VARCHAR(42) NOT NULL,
  chain_id BIGINT NOT NULL REFERENCES chains(id) ON DELETE RESTRICT,
  status TEXT NOT NULL CHECK (status IN ('CLAIMED','SIMULATING','SIGNING','SIGNED','SUBMITTED','PENDING','CONFIRMED','REVERTED','FAILED','SKIPPED','RETRY')),
  unsigned_transaction JSONB,
  copy_transaction_hash VARCHAR(66),
  nonce NUMERIC(78, 0),
  gas_estimate NUMERIC(78, 0),
  native_value NUMERIC(78, 0),
  block_number BIGINT,
  gas_used NUMERIC(78, 0),
  effective_gas_price NUMERIC(78, 0),
  failure_reason TEXT,
  retry_count INTEGER NOT NULL DEFAULT 0,
  pending_detected_at TIMESTAMPTZ,
  analysis_started_at TIMESTAMPTZ,
  analysis_completed_at TIMESTAMPTZ,
  simulation_started_at TIMESTAMPTZ,
  simulation_completed_at TIMESTAMPTZ,
  execution_started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  signing_started_at TIMESTAMPTZ,
  signed_at TIMESTAMPTZ,
  broadcast_started_at TIMESTAMPTZ,
  broadcast_completed_at TIMESTAMPTZ,
  confirmed_at TIMESTAMPTZ,
  failed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT execution_attempt_source_unique UNIQUE (chain_id, source_transaction_hash, destination_wallet)
);

CREATE INDEX execution_attempt_status_idx ON execution_attempts(status, updated_at);
CREATE INDEX execution_attempt_copy_hash_idx ON execution_attempts(copy_transaction_hash) WHERE copy_transaction_hash IS NOT NULL;
CREATE INDEX execution_attempt_wallet_chain_idx ON execution_attempts(destination_wallet, chain_id, status);
